### ISSUE TITLE
How is it different from time travelling in arangodb?

### ISSUE THREAD

**Issue by uday-uppal** [RecallGraph/RecallGraph#23]
https://www.arangodb.com/2018/07/time-traveling-with-graph-databases/

**Comment by adityamukho** [comment]
**Short answer:** They're different approaches to the same problem.
**Long answer:** Due to their differences in ground-up design and vision, there are a few significant differences. Here's an (incomplete) list:

1. RecallGraph (RG) is designed to be thought of and used in ways similar to software version control systems. Thus, it has APIs for fetching changelogs and diffs between document versions, similar to Git, for example.
2. RG does not impose any restrictions on the structure of the user's graph data that is versioned, whereas IIRC, ArangoDB's approach limits the user to DAGs only.
3. RG provides simple APIs to perform basic point-in-time traversals (no prune, post-filtering only), point-in-time lookups and point-in-time _k-shortest_path_ algorithms OOTB. In the design described in the blog, the queries to achieve these would have to be thought out and built by the end user.

Finally, although I do not have exact performance benchmarks, I reckon ArangoDB's structure could be faster for certain types of queries (since it does not have to rebuild historic data from deltas), whereas RG provides a more complete, tested and ready-to-use solution with potentially lesser ramp-up time.

**Caveat:** RG has not been actively developed for a while, and the last tested and compatible ArangoDB version was 3.6, which is quite outdated now.

To learn more, visit https://docs.recallgraph.tech/ and https://blog.recallgraph.tech/

**Comment by uday-uppal** [comment]
hi @adityamukho I was using recall graph in python(Django). So to hit the endpoints of Recall graph I used "requests.get()","requests.put()", etc., but this is reducing the performace greatly. With pyarango I created 2000 documents in 7 seconds, while with recall graph, only 170 nodes in 2 minutes. Is there any other way that I can use to improve the performace? Please help with this

**Comment by adityamukho** [comment]
Try 'Bulk Create'. See 
https://docs.recallgraph.tech/working-with-recallgraph/guide/persisting-documents/create 
for an example.

On 2022-09-19 13:16, Uday Uppal wrote:

> hi @adityamukho [1] I was using recall graph in python(Django). So to 
> hit the endpoints of Recall graph I used 
> "requests.get()","requests.put()", etc., but this is reducing the 
> performace greatly. With pyarango I created 2000 documents in 7 
> seconds, while with recall graph, only 170 nodes in 2 minutes. Is there 
> any other way that I can use to improve the performace? Please help 
> with this
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/adityamukho
[2] 
https://github.com/RecallGraph/RecallGraph/issues/23#issuecomment-1250680449
[3]
